import mongoose, { type Document, type Types } from 'mongoose';

const { Schema } = mongoose;

/**
 * Expertise mode enum
 */
export enum ExpertiseMode {
  PHYSICAL = 'physical',
  ONLINE = 'online',
  HYBRID = 'hybrid',
}

/**
 * Ticket type enum
 */
export enum TicketType {
  FREE = 'Free',
  PAID = 'Paid',
}

/**
 * Availability type enum
 */
export enum AvailabilityType {
  MANUAL = 'manual',
  FLEXIBLE = 'flexible',
  AUTOFILL = 'autofill',
}

/**
 * Expertise status enum
 */
export enum ExpertiseStatus {
  DRAFT = 'draft',
  PUBLISHED = 'published',
  ARCHIVED = 'archived',
}

/**
 * Link mode enum
 */
export enum LinkMode {
  SEND = 'send',
  DISPLAY = 'display',
}

/**
 * Question type enum
 */
export enum QuestionType {
  TEXT = 'text',
  DROPDOWN = 'dropdown',
  CHECKBOX = 'checkbox',
  MULTIPLE_CHOICE = 'multiple_choice',
}

/**
 * Location type enum
 */
export enum LocationType {
  HUB = 'hub',
  NEW = 'new',
  OTHER = 'other',
}

/**
 * Location interface for expertise venues
 */
export interface IExpertiseLocation {
  locationType?: LocationType;
  venueName?: string;
  autofill?: boolean;
  address?: string;
  country?: string;
  state?: string;
  city?: string;
  lat?: number;
  lng?: number;
}

/**
 * Operating day subdocument interface
 */
export interface IOperatingDay {
  key: string; // 'monday', 'tuesday', etc.
  fullTitle: string; // 'Monday', 'Tuesday', etc.
  title: string; // 'M', 'T', 'W', 'Th', 'F', 'Sa', 'Su'
  isActive: boolean;
  fullDay: boolean;
  startTime: string; // HH:mm format
  endTime: string; // HH:mm format
}

/**
 * Operating hours subdocument interface
 */
export interface IOperatingHours {
  autofill: boolean;
  sameOperatingHoursForAll: boolean;
  allOperatingHours: boolean;
  allOperatingStartTime?: string;
  allOperatingEndTime?: string;
  days: IOperatingDay[];
}

/**
 * Duration unit enum
 */
export enum DurationUnit {
  MINUTES = 'minutes',
  HOURS = 'hours',
}

/**
 * Ticket subdocument interface
 * Note: _id is auto-generated by Mongoose for subdocuments
 */
export interface ITicket {
  _id?: Types.ObjectId;
  ticketName: string;
  ticketType: TicketType;
  standardRate: number;
  ticketQty: number;
  description?: string;
  expertiseMode: ExpertiseMode;

  // Session Duration
  sessionDuration?: number;
  durationUnit?: DurationUnit;

  // Buffer Time
  hasBufferTime?: boolean;
  bufferTime?: number;

  // Booking Settings
  instantBooking?: boolean;
}

/**
 * Custom question subdocument interface
 */
export interface ICustomQuestion {
  questionLabel: string;
  questionType: QuestionType;
  saveStatus: boolean;
  dropDown?: string[];
  checkBox?: string[];
  multipleChoices?: string[];
}

/**
 * Custom questions subdocument interface
 */
export interface ICustomQuestions {
  isQuestionMandatory: boolean;
  questionArray: ICustomQuestion[];
}

/**
 * Host subdocument interface
 */
export interface IHost {
  id: string;
  name: string;
  email?: string;
  profileUrl: string;
  roleId?: string;
  description: string;
}

/**
 * Expertise document interface
 */
export interface IExpertise extends Document {
  // Section 1: Your Expertise
  expertiseTitle: string;
  expertiseDescription: string;
  expertiseSummary: string;
  host: IHost;
  tags: string[];
  primaryLanguage: string;
  secondaryLanguages: string[];
  slug: string;

  // Section 2: Booking Details
  linkMode: LinkMode;
  expertiseLink?: string;
  location?: IExpertiseLocation;
  coverPhoto: string;
  gallery: string[];
  expertiseInstructions?: string;
  customQuestions?: ICustomQuestions;

  // Section 3: Pricing
  feePaidBy: string;
  operatingHours?: IOperatingHours;
  availabilityType: AvailabilityType;
  ticket: ITicket[];
  audienceType?: string;

  // Additional Fields
  hubId: mongoose.Types.ObjectId;
  createdBy: mongoose.Types.ObjectId;
  status: ExpertiseStatus;
  currency: string;
  /** @deprecated Use reviewStats.averageRating instead */
  rating?: number;
  // Review Stats (aggregated from BookingReview)
  reviewStats?: {
    averageRating: number;
    totalReviews: number;
    ratingDistribution: {
      1: number;
      2: number;
      3: number;
      4: number;
      5: number;
    };
    lastReviewAt?: Date;
  };

  // Timestamps
  createdAt: Date;
  updatedAt: Date;

  // Migration tracking
  firebaseId?: string;
}

/**
 * Operating day schema
 */
const operatingDaySchema = new Schema<IOperatingDay>(
  {
    key: { type: String },
    fullTitle: { type: String },
    title: { type: String },
    isActive: { type: Boolean, default: false },
    fullDay: { type: Boolean, default: true },
    startTime: { type: String, default: '' },
    endTime: { type: String, default: '' },
  },
  { _id: false },
);

/**
 * Operating hours schema
 */
const operatingHoursSchema = new Schema<IOperatingHours>(
  {
    autofill: { type: Boolean, default: false },
    sameOperatingHoursForAll: { type: Boolean, default: false },
    allOperatingHours: { type: Boolean, default: false },
    allOperatingStartTime: { type: String },
    allOperatingEndTime: { type: String },
    days: { type: [operatingDaySchema], default: [] },
  },
  { _id: false },
);

/**
 * Ticket schema
 * Note: _id is auto-generated by Mongoose for each ticket subdocument
 */
const ticketSchema = new Schema<ITicket>({
  ticketName: { type: String },
  ticketType: {
    type: String,
    enum: Object.values(TicketType),
  },
  standardRate: { type: Number, min: 0 },
  ticketQty: { type: Number, min: 0 },
  description: { type: String },
  expertiseMode: {
    type: String,
    enum: Object.values(ExpertiseMode),
  },

  // Session Duration
  sessionDuration: { type: Number },
  durationUnit: {
    type: String,
    enum: Object.values(DurationUnit),
    default: DurationUnit.MINUTES,
  },

  // Buffer Time
  hasBufferTime: { type: Boolean, default: false },
  bufferTime: { type: Number },

  // Booking Settings
  instantBooking: { type: Boolean, default: false },
});

/**
 * Custom question schema
 */
const customQuestionSchema = new Schema<ICustomQuestion>(
  {
    questionLabel: { type: String },
    questionType: {
      type: String,
      enum: Object.values(QuestionType),
    },
    saveStatus: { type: Boolean, default: false },
    dropDown: { type: [String] },
    checkBox: { type: [String] },
    multipleChoices: { type: [String] },
  },
  { _id: false },
);

/**
 * Custom questions schema
 */
const customQuestionsSchema = new Schema<ICustomQuestions>(
  {
    isQuestionMandatory: { type: Boolean, default: false },
    questionArray: { type: [customQuestionSchema], default: [] },
  },
  { _id: false },
);

/**
 * Host schema
 */
const hostSchema = new Schema<IHost>(
  {
    id: { type: String },
    name: { type: String },
    email: { type: String },
    profileUrl: { type: String },
    roleId: { type: String },
    description: { type: String },
  },
  { _id: false },
);

/**
 * Location schema
 */
const locationSchema = new Schema<IExpertiseLocation>(
  {
    locationType: { type: String, enum: Object.values(LocationType) },
    venueName: { type: String },
    autofill: { type: Boolean, default: false },
    address: { type: String },
    country: { type: String },
    state: { type: String },
    city: { type: String },
    lat: { type: Number },
    lng: { type: Number },
  },
  { _id: false },
);

/**
 * Expertise schema definition
 */
const expertiseSchema = new Schema<IExpertise>(
  {
    // Section 1: Your Expertise
    expertiseTitle: {
      type: String,
      trim: true,
      maxlength: 200,
      index: true,
    },
    expertiseDescription: {
      type: String,
    },
    expertiseSummary: {
      type: String,
      maxlength: 200,
    },
    host: {
      type: hostSchema,
    },
    tags: {
      type: [String],
      default: [],
    },
    primaryLanguage: {
      type: String,
      default: 'English',
    },
    secondaryLanguages: {
      type: [String],
      default: [],
    },
    slug: {
      type: String,
      unique: true,
      sparse: true, // Allow null/undefined for drafts
      lowercase: true,
      trim: true,
      index: true,
    },

    // Section 2: Booking Details
    linkMode: {
      type: String,
      enum: Object.values(LinkMode),
      default: LinkMode.SEND,
    },
    expertiseLink: {
      type: String,
    },
    location: {
      type: locationSchema,
    },
    coverPhoto: {
      type: String,
    },
    gallery: {
      type: [String],
      default: [],
    },
    expertiseInstructions: {
      type: String,
      maxlength: 500,
    },
    customQuestions: {
      type: customQuestionsSchema,
    },

    // Section 3: Pricing
    feePaidBy: {
      type: String,
      default: 'learner',
    },
    operatingHours: {
      type: operatingHoursSchema,
    },
    availabilityType: {
      type: String,
      enum: Object.values(AvailabilityType),
      default: AvailabilityType.MANUAL,
    },
    ticket: {
      type: [ticketSchema],
      default: [],
    },
    audienceType: {
      type: String,
    },

    // Additional Fields
    hubId: {
      type: Schema.Types.ObjectId,
      ref: 'Hub',
      index: true,
    },
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      index: true,
    },
    status: {
      type: String,
      enum: Object.values(ExpertiseStatus),
      default: ExpertiseStatus.DRAFT,
      index: true,
    },
    currency: {
      type: String,
      uppercase: true,
      default: 'MYR',
    },
    /** @deprecated Use reviewStats.averageRating instead */
    rating: {
      type: Number,
      min: 0,
      max: 5,
    },

    // Review Stats (aggregated from BookingReview)
    reviewStats: {
      type: {
        averageRating: { type: Number, default: 0, min: 0, max: 5 },
        totalReviews: { type: Number, default: 0, min: 0 },
        ratingDistribution: {
          type: {
            1: { type: Number, default: 0 },
            2: { type: Number, default: 0 },
            3: { type: Number, default: 0 },
            4: { type: Number, default: 0 },
            5: { type: Number, default: 0 },
          },
          default: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 },
        },
        lastReviewAt: { type: Date },
      },
      default: {
        averageRating: 0,
        totalReviews: 0,
        ratingDistribution: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 },
      },
    },

    // Migration tracking
    firebaseId: {
      type: String,
      sparse: true,
      index: true,
    },
  },
  {
    timestamps: true,
    collection: 'expertises',
    toJSON: {
      transform: (_doc, ret) => {
        const { __v: _v, ...rest } = ret;
        return rest;
      },
    },
    toObject: {
      transform: (_doc, ret) => {
        const { __v: _v, ...rest } = ret;
        return rest;
      },
    },
  },
);

// Compound indexes for performance optimization
expertiseSchema.index({ hubId: 1, status: 1 }); // Hub expertises by status
expertiseSchema.index({ createdBy: 1, status: 1 }); // User expertises by status
expertiseSchema.index({ slug: 1, hubId: 1 }); // Unique expertise lookup
expertiseSchema.index({ createdAt: -1 }); // Recent expertises
expertiseSchema.index({ rating: -1 }); // Top rated expertises

// Text index for search
expertiseSchema.index({
  expertiseTitle: 'text',
  expertiseSummary: 'text',
  expertiseDescription: 'text',
});

/**
 * Expertise model
 */
export const Expertise = mongoose.model<IExpertise>('Expertise', expertiseSchema);
