import mongoose, { type Document, type Types } from 'mongoose';

const { Schema } = mongoose;

/**
 * Location interface for experience venues
 */
export interface IExperienceLocation {
  locationType?: 'hub' | 'new' | 'other'; // Type of location selection
  venueName?: string; // Venue name (for 'other' type)
  autofill?: boolean;
  address: string;
  country: string;
  state: string;
  city: string;
  lat?: number;
  lng?: number;
}

/**
 * Experience topic reference
 */
export interface IExperienceTopicRef {
  theme: string; // Theme ID
  topic: string; // Topic ID
}

/**
 * Host/Expert details for experience
 */
export interface IExperienceHost {
  userId?: string;
  name?: string;
  email?: string;
  photoUrl?: string;
  roleId?: string;
  description?: string;
}

/**
 * Experience ticket definition
 * Note: _id is auto-generated by Mongoose for subdocuments
 */
export interface IExperienceTicket {
  _id?: Types.ObjectId;
  ticketType: string; // "Paid" or "Free"
  ticketName: string;
  ticketPrice: number;
  ticketQty: number;
  cutoffNumber?: number;
  cutoffTime?: string;
  cutoffBeforeAfter?: string;
  description?: string;
  hasCutoffTime?: boolean;
}

/**
 * Schedule/Recurring event configuration
 */
export interface IExperienceSchedule {
  uid: string;
  recurringRule: string[]; // Days of week, dates, etc.
  startDate: string | Date;
  endDate?: string | Date; // For multi-day or bounded recurring events
  recurringType: string; // "daily", "weekly", "monthly", "once", "no_repeat"
}

/**
 * Custom form question
 */
export interface ICustomQuestion {
  questionLabel: string;
  questionType: string; // "text", "dropdown", "checkbox", "multiple_choice"
  saveStatus?: boolean;
  dropDown?: string[];
  checkBox?: string[];
  multipleChoices?: string[];
}

/**
 * Experience Interface
 * Main experience/event model with comprehensive fields
 */
export interface IExperience extends Document {
  // Basic Information
  experienceTitle: string;
  slug: string;
  experienceDescription?: string; // Optional for express experiences
  experienceType: 'Physical' | 'Virtual' | 'Hybrid';
  hubId: string | Types.ObjectId; // Reference to Hub

  // Category and Topics
  experienceCategory?: string | Types.ObjectId; // Optional for express experiences - Reference to ExperienceTheme
  experienceTopics?: IExperienceTopicRef[]; // Optional for express experiences

  // Location (for Physical/Hybrid)
  location?: IExperienceLocation;
  timeZone?: string;

  // Virtual Meeting Info (for Virtual/Hybrid)
  meetingLink?: string;
  meetingLocation?: string;
  zoomMeetingData?: Record<string, unknown>;
  meetingLinkEditedDate?: Date;

  // Host Information
  hostDetails: IExperienceHost[];
  noHost: boolean;

  // Audience Settings
  audienceType: 'Everyone' | 'Members Only' | 'Hidden' | 'PUBLIC' | 'PRIVATE';
  maximumCapacity?: number;
  canBookAsPrivate: boolean;
  targetAudience: string[]; // Array of audience type names
  expertiseLevel?: string;
  expertiseFields?: string[];

  // Languages
  primaryLanguage?: string; // Optional for express experiences
  secondaryLanguage?: string[];

  // Pricing
  feePaidBy: 'learner' | 'hub';
  currency: string;
  currencyType?: string;

  // Ticketing
  ticket?: IExperienceTicket[];

  // Booking Settings
  experienceDuration?: number; // In milliseconds

  // Schedules
  schedules?: IExperienceSchedule[];

  // Content/Media
  coverPhoto?: string;
  gallery?: string[];
  video?: string;
  poster?: string;
  sopPoster?: string;
  showAutoImage?: boolean;

  // Additional Information
  learnerOutcome?: string;
  instruction?: string;
  materialProvided?: string; // Frontend sends string, not array
  materialNeedToBring?: string; // Frontend sends string, not array
  sopInformation?: string;

  // Custom Questions
  customQuestions?: {
    isQuestionMandatory?: boolean;
    questionArray?: ICustomQuestion[];
  };
  customFormJSON?: Record<string, unknown>;

  // Metadata
  status: 'ACTIVE' | 'DRAFTED' | 'DELETED' | 'EXPIRED';
  type?: string; // "platform" or other
  listingType: 'platform' | 'express'; // Distinguish experience variant
  priority: number;
  isFeatured: boolean;
  isShowCaseOnProfile?: boolean;
  views: number;
  /** @deprecated Use reviewStats.averageRating instead */
  rating?: number;
  // Review Stats (aggregated from BookingReview)
  reviewStats?: {
    averageRating: number;
    totalReviews: number;
    ratingDistribution: {
      1: number;
      2: number;
      3: number;
      4: number;
      5: number;
    };
    lastReviewAt?: Date;
  };

  // Service reference
  service?: {
    $key: string;
  };

  // Audit fields
  createdBy?: string | Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;

  // Migration tracking
  firebaseId?: string;
}

/**
 * Location sub-schema
 */
const locationSchema = new Schema<IExperienceLocation>(
  {
    locationType: { type: String, enum: ['hub', 'new', 'other'] },
    venueName: { type: String, trim: true },
    autofill: Boolean,
    address: { type: String, trim: true },
    country: { type: String, trim: true },
    state: { type: String, trim: true },
    city: { type: String, trim: true },
    lat: Number,
    lng: Number,
  },
  { _id: false },
);

/**
 * Topic reference sub-schema
 */
const topicRefSchema = new Schema<IExperienceTopicRef>(
  {
    theme: { type: String },
    topic: { type: String },
  },
  { _id: false },
);

/**
 * Host details sub-schema
 */
const hostSchema = new Schema<IExperienceHost>(
  {
    userId: String,
    name: String,
    email: String,
    photoUrl: String,
    roleId: String,
    description: String,
  },
  { _id: false },
);

/**
 * Ticket sub-schema
 * Note: _id is auto-generated by Mongoose for each ticket subdocument
 */
const ticketSchema = new Schema<IExperienceTicket>({
  ticketType: { type: String },
  ticketName: { type: String },
  ticketPrice: { type: Number },
  ticketQty: { type: Number },
  cutoffNumber: Number,
  cutoffTime: String,
  cutoffBeforeAfter: String,
  description: String,
  hasCutoffTime: Boolean,
});

/**
 * Schedule sub-schema
 */
const scheduleSchema = new Schema<IExperienceSchedule>(
  {
    uid: { type: String },
    recurringRule: [String],
    startDate: { type: Schema.Types.Mixed },
    recurringType: { type: String },
    endDate: { type: Schema.Types.Mixed },
  },
  { _id: false },
);

/**
 * Custom question sub-schema
 */
const customQuestionSchema = new Schema<ICustomQuestion>(
  {
    questionLabel: { type: String },
    questionType: { type: String },
    saveStatus: Boolean,
    dropDown: [String],
    checkBox: [String],
    multipleChoices: [String],
  },
  { _id: false },
);

/**
 * Experience schema definition
 */
const experienceSchema = new Schema<IExperience>(
  {
    // Basic Information
    experienceTitle: {
      type: String,
      trim: true,
      index: true,
    },
    slug: {
      type: String,
      unique: true,
      sparse: true, // Allow null/undefined for drafts
      trim: true,
      lowercase: true,
      index: true,
    },
    experienceDescription: {
      type: String,
      trim: true,
      default: '',
    },
    experienceType: {
      type: String,
      enum: ['Physical', 'Virtual', 'Hybrid'],
      index: true,
    },
    hubId: {
      type: Schema.Types.Mixed, // Can be String or ObjectId
      index: true,
    },

    // Category and Topics
    experienceCategory: {
      type: Schema.Types.Mixed,
      required: false, // Optional for express experiences
      index: true,
    },
    experienceTopics: {
      type: [topicRefSchema],
      required: false, // Optional for express experiences
      default: [], // Default empty array for express experiences
    },

    // Location
    location: locationSchema,
    timeZone: String,

    // Virtual Meeting Info
    meetingLink: String,
    meetingLocation: String,
    zoomMeetingData: Schema.Types.Mixed,
    meetingLinkEditedDate: Date,

    // Host Information
    hostDetails: {
      type: [hostSchema],
      default: [],
    },
    noHost: {
      type: Boolean,
      default: false,
    },

    // Audience Settings
    audienceType: {
      type: String,
      enum: ['Everyone', 'Members Only', 'Hidden', 'PUBLIC', 'PRIVATE'],
      default: 'Everyone',
      index: true,
    },
    maximumCapacity: Number,
    canBookAsPrivate: {
      type: Boolean,
      default: false,
    },
    targetAudience: {
      type: [String],
      default: [],
    },
    expertiseLevel: String,
    expertiseFields: [String],

    // Languages
    primaryLanguage: {
      type: String,
      required: false, // Optional for express experiences
      default: 'English', // Default language for express experiences
    },
    secondaryLanguage: [String],

    // Pricing
    feePaidBy: {
      type: String,
      enum: ['learner', 'hub'],
      default: 'learner',
    },
    currency: {
      type: String,
      default: 'MYR',
    },
    currencyType: String,

    // Ticketing
    ticket: [ticketSchema],

    // Booking Settings
    experienceDuration: Number,

    // Schedules
    schedules: [scheduleSchema],

    // Content/Media
    coverPhoto: String,
    gallery: [String],
    video: String,
    poster: String,
    sopPoster: String,
    showAutoImage: Boolean,

    // Additional Information
    learnerOutcome: String,
    instruction: String,
    materialProvided: String, // Frontend sends string, not array
    materialNeedToBring: String, // Frontend sends string, not array
    sopInformation: String,

    // Custom Questions
    customQuestions: {
      type: {
        isQuestionMandatory: Boolean,
        questionArray: [customQuestionSchema],
      },
      default: {},
    },
    customFormJSON: Schema.Types.Mixed,

    // Metadata
    status: {
      type: String,
      enum: ['ACTIVE', 'DRAFTED', 'DELETED', 'EXPIRED'],
      default: 'DRAFTED',
      index: true,
    },
    type: {
      type: String,
      default: 'platform',
    },
    listingType: {
      type: String,
      enum: ['platform', 'express'],
      default: 'platform',
      index: true,
    },
    priority: {
      type: Number,
      default: 1000,
      index: true,
    },
    isFeatured: {
      type: Boolean,
      default: false,
      index: true,
    },
    isShowCaseOnProfile: Boolean,
    views: {
      type: Number,
      default: 0,
    },
    /** @deprecated Use reviewStats.averageRating instead */
    rating: Number,

    // Review Stats (aggregated from BookingReview)
    reviewStats: {
      type: {
        averageRating: { type: Number, default: 0, min: 0, max: 5 },
        totalReviews: { type: Number, default: 0, min: 0 },
        ratingDistribution: {
          type: {
            1: { type: Number, default: 0 },
            2: { type: Number, default: 0 },
            3: { type: Number, default: 0 },
            4: { type: Number, default: 0 },
            5: { type: Number, default: 0 },
          },
          default: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 },
        },
        lastReviewAt: { type: Date },
      },
      default: {
        averageRating: 0,
        totalReviews: 0,
        ratingDistribution: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 },
      },
    },

    // Service reference
    service: {
      type: {
        $key: String,
      },
      default: undefined,
    },

    // Audit fields
    createdBy: Schema.Types.Mixed,

    // Migration tracking
    firebaseId: {
      type: String,
      sparse: true,
      index: true,
    },
  },
  {
    timestamps: true,
    toJSON: {
      transform: (_doc, ret: Record<string, unknown>) => {
        // Remove __v from output
        delete ret.__v;
        return ret;
      },
    },
  },
);

// Compound indexes for efficient queries
experienceSchema.index({ hubId: 1, status: 1 });
experienceSchema.index({ slug: 1 });
experienceSchema.index({ status: 1, audienceType: 1 });
experienceSchema.index({ isFeatured: 1, status: 1 });
experienceSchema.index({ createdAt: -1 });
experienceSchema.index({ priority: 1, status: 1 });
experienceSchema.index({ experienceType: 1, status: 1 });
experienceSchema.index({ experienceCategory: 1, status: 1 });

// Text index for search
experienceSchema.index({
  experienceTitle: 'text',
  experienceDescription: 'text',
});

export const Experience = mongoose.model<IExperience>('Experience', experienceSchema);

// Type aliases for convenience
export type ISchedule = IExperienceSchedule;
export type ITicket = IExperienceTicket;
