apiVersion: v2
name: mereka-auth
description: Mereka uauth Application (SSR)
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - mereka
  - web
  - angular
  - ssr
maintainers:
  - name: BBI Team
