apiVersion: v2
name: mereka-admin
description: Mereka uadmin Application (SSR)
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - mereka
  - web
  - angular
  - ssr
maintainers:
  - name: BBI Team
