apiVersion: v1
kind: ConfigMap
metadata:
  name: mereka-backend-config
  labels:
    {{- include "mereka-backend.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  FRONTEND_URL: {{ .Values.config.frontendUrl | quote }}
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
